### ISSUE TITLE
Issue with Expanded Menus.

### ISSUE THREAD

**Issue by yiiyahui** [easonwong-de/Adaptive-Tab-Bar-Colour#101]
HI.

I tried version 2.21. If I do not want the panel/menu to be controlled by the extension, I add the following content in CSS. Here is an example:

```css
:root[lwtheme] panel {
	color-scheme: light dark !important;
}
```
![1](https://github.com/user-attachments/assets/99e888eb-b8f4-40fc-9d8f-3921cd7f42aa)

The browser's toolbar pop-up menu only follows light/dark, and at this point, the background color of the extension's control menu will not change, but the text color will follow light/dark. 
This issue does not occur under the default theme.

BTW: I do not want the extension to control the background color of the panel/menu because in some high-contrast colors, such as red or green, it can be very glaring.
![2](https://github.com/user-attachments/assets/ae2b170c-692d-4d0e-ad79-54ba5dfa7a61)

----

 It seems that when I set a background color for a certain element, it cannot be rendered by the extension. For example:

```css
.tab-background {
	background-color: transparent;
	&[selected] {
		background-color: color-mix(in srgb, currentColor 10%, transparent);
	}
}
```
Thank you!

**Comment by easonwong-de** [comment]
Hi, @yiiyahui! Thanks for trying out the new version.

> the background color of the extension’s control menu will not change, but the text color will follow light/dark.

This happens because the text colour of the extension’s menu is decided by pop-up’s colour scheme (`@media (prefers-color-scheme: dark)`, in this case it’s changed to `light`), whilst its background colour is set to the pop-up colour (equals to `--panel-background` in CSS if it’s not overwritten) of the Firefox theme via JavaScript.

If I give a transparent background to the extension’s menu, it’ll look like this in dark mode:

<img src="https://github.com/user-attachments/assets/fcc4fa43-8358-4331-997e-ad0e5c6134dc" width="50%" ><br>

This is because the default background of the extension pop-up is pure white.

But also, I’m quite surprised that `color-scheme: light dark !important;` can revert the pop-ups to their default colours. I’ll do some testing on that.

<hr>

Starting with version v2.2+, you can adjust the minimum contrast between the tab bar colour and its text. I checked the contrast ratio in your screenshot, which came out as $6.15$. Since the minimum contrast ratio for light mode is $16.5$, I’m assuming your browser was in dark mode. You might want to increase the minimum contrast ratio for dark mode to make it less jarring.

Also, I am planning to add the possibility to set certain colours to UI elements in the future, as tracked in #38 and #88. That may help your CSS theme work better.

<hr>

I think it’s probably because `currentColor` is the text colour of the element. Maybe you can try to use this:

```css
.tab-background {
	background-color: transparent;
	&[selected] {
		background-color: color-mix(in srgb, var(--tab-selected-bgcolor) 10%, transparent);
	}
}
```

**Comment by easonwong-de** [comment]
P.S. The “Theme builder” won’t have the horizontal scrollbar in the next update, thanks for the screenshot!

**Comment by yiiyahui** [comment]
Thank you for your reply. I'm glad to hear that this extension has been updated and that the color issues present in some older versions have been fixed.

Regarding the panel colors, if the CSS is as follows:

```css
/*userchrome.css*/
:root {
	/*panel background*/
	--arrowpanel-background: light-dark(#f2f2f2, #333) !important;
	/*text color*/
	--panel-color: MenuText !important;
}

:root[lwtheme] panel {
	color-scheme: light dark !important;
}
```

Yes, the issue is that the extension menu color is not being overridden by the CSS. I believe there are many examples of changing the background color of `--arrowpanel-background` in CSS, but if `ATBC` is used without setting the `color-scheme`, the result is that even if the text color is configured, it won't be perfect, Just like this. Of course, in most cases, it doesn't affect usage.

![3](https://github.com/user-attachments/assets/0f5dbc8b-598b-492f-992a-52498a879140)

----

The second question is a doubt; I didn't fully understand the update notes before, but now I think I do.

----
Another new issue is that the color of the toolbar on the `"about:"` page does not follow the color settings of the home page.
![4](https://github.com/user-attachments/assets/dc0635d2-59c0-413c-b2a3-d43babb1d6ca)
