### ISSUE TITLE
Support for changing the context menu color

### ISSUE THREAD

**Issue by def00111** [easonwong-de/Adaptive-Tab-Bar-Colour#114]
It maybe useful to also change the context menu color. I created a [bug 1946982](https://bugzilla.mozilla.org/show_bug.cgi?id=1946982) for this feature request. Maybe you can write there that it maybe useful for your add-on?

**Comment by easonwong-de** [comment]
I agree! And thanks for your report at Bugzilla.

Once the context menu background can be controlled by [theme API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme), feel free to let me know! I usually develop on macOS, where Firefox uses system native context menu.

For now, I would suggest using a [CSS theme](https://www.userchrome.org/) to change the look of the context menu.

**Comment by easonwong-de** [comment]
Hi, adding this to your custom CSS will apply adaptive theme to the context menu:

```css
:is(menupopup, panel):where(:not([type="arrow"])) {
    --panel-background-color: unset !important;
    --panel-border-color: unset !important;
}
```

These configs need to be changed to `false`:

```
widget.gtk.native-context-menus
widget.macos.native-context-menus
```

I’ll close this issue for now, because I don’t think Mozilla will implement [Bug 1946981](https://bugzilla.mozilla.org/show_bug.cgi?id=1946981) anytime soon.
