### ISSUE TITLE
Compatibility and support for experimental vertical tabs sidebar

### ISSUE THREAD

**Issue by xplosionmind** [easonwong-de/Adaptive-Tab-Bar-Colour#115]
I am finding it very annoying that there is a shadow around the content frame, while this extension is purposefully built to have a seamless transition between the content of a page and the browser tools.

![Image](https://github.com/user-attachments/assets/9da983e5-87c6-49fc-a003-7f20aae348c7)

Is it something related to this extension?

**Comment by xplosionmind** [comment]
Thanks @easonwong-de!

I got what I needed by adding the following to `userChrome.css`:

```css
#tabbrowser-tabbox {
	outline: none !important;
	box-shadow: none !important;
}
```
