### ISSUE TITLE
Smooth Transition Between Colour Change

### ISSUE THREAD

**Issue by ghost** [easonwong-de/Adaptive-Tab-Bar-Colour#43]
Currently when we change the tab, the colour flashes, it would be a nice toggle addon to enable if we wish to set time delay and transition colour slowly instead of direct flash.

**Comment by YS-Wong** [comment]
The best solution might be adding transition for `background-color` in `userChrome.css`.

Moreover, I’m working on a newer version. Which should eliminate unwanted colour changes.

**Comment by dpthegrey** [comment]
Alright! Thanks, I'll try experimenting with adding youtube like ambient mode type switching for tabs.

**Comment by sebihotza** [comment]
> The best solution might be adding transition for `background-color` in `userChrome.css`.
> 
> Moreover, I’m working on a newer version. Which should eliminate unwanted colour changes.

Could you tell me how to do that? Which element do I need to add transition to?

**Comment by sertchan** [comment]
I've same question with sebihotza. I wonder how could i make transition 👀

**Comment by YS-Wong** [comment]
Easiest way:

`userChrome.css`

```
#sidebar-box *,
#navigator-toolbox-background * {
    transition: background-color 1s ease-out;
}
```

If you wonder how to find this file, visit https://www.userchrome.org/

**Comment by mizlan** [comment]
For me, this only causes the URL bar and background tab color to change, not the toolbar color / active tab color

**Comment by jacksongoode** [comment]
Bumping!

**Comment by Moarram** [comment]
I finally figured out how to transition the active tab too! Here is my `userChrome.css`:
```css
#sidebar-box *,
#urlbar-background,
#navigator-toolbox {
  transition: background-color .5s cubic-bezier(0, 0, 0, 1);
}
.tab-background {
  transition: background-color .5s cubic-bezier(0, 0, 0, 1);
  box-shadow: none !important;
  background-image: none !important;
}
.tab-background[selected] {
  background-color: var(--lwt-selected-tab-background-color) !important;
}
```
I love this plugin and this definitely takes it to the next level :)

**Comment by elken** [comment]
> I finally figured out how to transition the active tab too! Here is my `userChrome.css`:
> 
> ```css
> #sidebar-box *,
> #urlbar-background,
> #navigator-toolbox {
>   transition: background-color .5s cubic-bezier(0, 0, 0, 1);
> }
> .tab-background {
>   transition: background-color .5s cubic-bezier(0, 0, 0, 1);
>   box-shadow: none !important;
>   background-image: none !important;
> }
> .tab-background[selected] {
>   background-color: var(--lwt-selected-tab-background-color) !important;
> }
> ```
> 
> I love this extension and the transitions definitely take it to the next level :)

Can confirm this works very well!

**Comment by elken** [comment]
Just reporting back that `--lwt-selected-tab-background-color` might not work on newer versions of Firefox; `--tab-selected-bgcolor` seems to still work though so the snippet should now be

```css
#sidebar-box *,
#urlbar-background,
#navigator-toolbox {
  transition: background-color .5s cubic-bezier(0, 0, 0, 1);
}
.tab-background {
  transition: background-color .5s cubic-bezier(0, 0, 0, 1);
  box-shadow: none !important;
  background-image: none !important;
}
.tab-background[selected] {
  background-color: var(--tab-selected-bgcolor) !important;
}
```
