### ISSUE TITLE
Add control over prefers-color-scheme

### ISSUE THREAD

**Issue by Neikon** [easonwong-de/Adaptive-Tab-Bar-Colour#60]
Vidaldifox changes this preference when you visit a dark/light website to configure it according to the website. 

Would a similar behavior be possible with this add-on? 

So we could configure features like this in our css themes: 
```css
@media (prefers-color-scheme: dark){ :root{
   --auto-accent-color: color-mix(in srgb, var(--lwt-accent-color) 80%, white);
}}
@media (prefers-color-scheme: light){ :root{
   --auto-accent-color: color-mix(in srgb, var(--lwt-accent-color) 80%, black);
}}
```

look at, this borde color is set with this css but I can not do it with this add-on only with VivaldiFox
![img (1)](https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour/assets/1765319/776918ac-625d-44bb-ae99-5c9a87aa63d9)
![img (2)](https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour/assets/1765319/59385813-c94f-4638-ab0f-5a357b6f8c7b)

 [VidaldiFox repo](https://github.com/nt1m/vivaldi-fox/tree/master)
